### ISSUE TITLE
Macro causes problem when used in the middle of a statement

### ISSUE THREAD

**Issue by PabstMirror** [LordGolias/sqf#11]
```
a &&
#ifdef ALLOW_QUICK_THROW
{b1} &&
#else
{b2} &&
#endif
{c}
```
```
    [1,2]:error:can't interpret statement (missing ;?): <Variable(a)> <Keyword(&&)>
    [2,5]:error:can't interpret statement (missing ;?): <Code({b1})> <Keyword(&&)>
    [3,5]:error:can't interpret statement (missing ;?): <Code({b2})> <Keyword(&&)>
```

**Comment by LordGolias** [comment]
Not easily solved because the parser cannot decide, without knowing about `ALLOW_QUICK_THROW´, whether `a && ` is syntactically wrong or not. 

In principle, this could be solved by evaluating both branches, `a && {b1} && {c}` and `a && {b2} && {c}`, but this is challenging because they could cause completely different things (e.g. one branch is error, the other not). 

I am doing that in some sense to evaluate `if-then`, but this is at the level of the parser, not the analyzer, so it is a bit harder to tackle.

**Comment by jonpas** [comment]
It is rare, maybe have it as a warning rather than error?

**Comment by LordGolias** [comment]
Fixed in 7ac5ec9052d0ca34e5afe815f2436fd8be83661c

Essentially, the parser now parses `#ifdef` and friends, taking the branch whose `#defined` variables are in the script (i.e. `#defines` that are `#included` are currently not taken into account).

**Comment by PabstMirror** [comment]
```
if (x1) then {
    systemChat "A";
#ifdef DEBUG_MODE_FULL
} else {
    systemChat "B";
#endif
};
```
will crash with:
```
Traceback (most recent call last):
  File "V:\sqf\sqflint.py", line 98, in <module>
    _main()
  File "V:\sqf\sqflint.py", line 94, in _main
    main(sys.argv[1:])
  File "V:\sqf\sqflint.py", line 86, in main
    analyze(code, writer)
  File "V:\sqf\sqflint.py", line 20, in analyze
    result = parse(code)
  File "V:\sqf\sqf\parser.py", line 543, in parse
    result = parse_block(tokens + [EndOfFile()], _analyze_tokens)[0]
  File "V:\sqf\sqf\parser.py", line 428, in parse_block
    expression, size = parse_block(all_tokens, analyze_tokens, i + 1, lvls, stop_statement, defines=defines)
  File "V:\sqf\sqf\parser.py", line 476, in parse_block
    assert(isinstance(expression, IfDefStatement))
AssertionError
```

**Comment by LordGolias** [comment]
Yeah, I am aware of that case (and that ACE has one file with that :) ). Between parenthesis is still not solved (nor unit-tested)

**Comment by LordGolias** [comment]
@PabstMirror, I pushed a fix that, while does not solve the problem entirely, it does avoid that crash and just raises an `SQFParserError` saying that parenthesis are not balanced or something.

**Comment by jonpas** [comment]
This is still being problematic for some cases - https://github.com/IDI-Systems/acre2/issues/346#issuecomment-307136574
