### ISSUE TITLE
Compile list of test cases for #define

### ISSUE THREAD

**Issue by LordGolias** [LordGolias/sqf#21]
I created [a new branch](https://github.com/LordGolias/sqf/tree/parse_define) with a working implementation of analysis of `#define` statements, including the 4 common cases

```
#define A
#define A (...)
#define A a,b,...
#define A(a,b,...) (a + b * ...)
```

I pushed this to a branch because I am not so familiar with the exact syntax of `#define`, and this may raise lots of errors if not done correctly.

I would like to ask for help in compiling a list of cases where the parser is expected to break, and cases which it does not. The goal is to, before moving to the ACE/ACRE/Exile code, have a solid list of simpler examples to test from.

**Comment by SilentSpike** [comment]
Some helpful pages:
https://community.bistudio.com/wiki/PreProcessor_Commands
https://community.bistudio.com/wiki/PreProcessor_Errors

**Comment by SilentSpike** [comment]
I'm not even sure if it's possible to break `#define`, as far as I know it'll just take all of the remainder of the line no matter the contents. With the `\` at EOL carrying the definition over to the next line.

I'm not sure what happens if you do:
```
#define \
#define
```

**Comment by LordGolias** [comment]
I compiled and addressed a list of `#define` test cases. I am sure it is not bullet-proof against everything, but it should cover the relevant use-cases.

I have not included the last one you mentioned because it seems a bit too edgy. Once we know what we should expect, and if it is worth caring about, we can address it.

Thanks a lot for the list of resources!

The relevant commit that addresses this is e0195cd883520e3.
