### ISSUE TITLE
Linter doesn't know how to interpret one line

### ISSUE THREAD

**Issue by CreepPork** [LordGolias/sqf#30]
The linter fails to recognize this as valid code (it runs perfectly well in-game):
```sqf
with uiNamespace do {call compile format ["[""LOADED"", controlNull] call (missionNamespace getVariable ""%1"");", _resource_fnc]};
```
It fails recognizing that `with uiNamespace do` is valid.

**Comment by LordGolias** [comment]
Can't reproduce:

```python
    def test_bla(self):
        code = 'with uiNamespace do {call compile format ["[""LOADED"", controlNull] call (missionNamespace getVariable ""%1"");", _resource_fnc]};'
        analyzer = analyze(parse(code))
        self.assertEqual(len(analyzer.exceptions), 1)
        print(analyzer.exceptions)
```

shows that the only error is the undefined `_resource_fnc`, which is a valid error.

See e.g. [this test](https://github.com/LordGolias/sqf/blob/master/tests/test_analyzer.py#L400) that tests the usage of the `with namespace` clause.

**Comment by CreepPork** [comment]
The error only occurs when using the [VS Code](https://github.com/SkaceKamen/vscode-sqflint) linter. Which are two different things.

**Comment by CreepPork** [comment]
While we're here, you're not planning this linter's implementation in VS Code?

**Comment by LordGolias** [comment]
what do you mean? Making it possible to use a lint on VS, or port this lint to VS code?

**Comment by DAmNRelentless** [comment]
There is already a sqf linter on VS Code

**Comment by CreepPork** [comment]
@LordGolias The same way you did it with Atom.

@DAmNRelentless There is but it doesn't seem as reliable and seems unstable and uses a lot of system resources.
