### ISSUE TITLE
TypeError in Parser/Tokenizer for `isNil format []`

### ISSUE THREAD

**Issue by shadow-fa** [LordGolias/sqf#35]
I get a `TypeError: expected string or bytes-like object` when running the following code:

```python
code = 'x = isNil format ["x"];'
errors = sqf.analyzer.analyze(sqf.parser.parse(code))
```

> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "C:\Program Files\Python36\lib\site-packages\sqf\analyzer.py", line 542, in analyze
>     analyzer.execute_code(file, extra_scope={'_this': arg})
>   File "C:\Program Files\Python36\lib\site-packages\sqf\analyzer.py", line 197, in execute_code
>     outcome = super().execute_code(code, extra_scope, namespace_name)
>   File "C:\Program Files\Python36\lib\site-packages\sqf\base_interpreter.py", line 177, in execute_code
>     token = self.execute_token(statement)
>   File "C:\Program Files\Python36\lib\site-packages\sqf\analyzer.py", line 150, in execute_token
>     result = self.execute_single(statement=token)
>   File "C:\Program Files\Python36\lib\site-packages\sqf\analyzer.py", line 340, in execute_single
>     rhs_v = self.value(base_tokens[2])
>   File "C:\Program Files\Python36\lib\site-packages\sqf\analyzer.py", line 111, in value
>     result = self.value(self.execute_token(token))
>   File "C:\Program Files\Python36\lib\site-packages\sqf\analyzer.py", line 150, in execute_token
>     result = self.execute_single(statement=token)
>   File "C:\Program Files\Python36\lib\site-packages\sqf\analyzer.py", line 373, in execute_single
>     t = self.execute_token(token)
>   File "C:\Program Files\Python36\lib\site-packages\sqf\analyzer.py", line 150, in execute_token
>     result = self.execute_single(statement=token)
>   File "C:\Program Files\Python36\lib\site-packages\sqf\analyzer.py", line 395, in execute_single
>     code = Code([parse(values[code_position].value)])
>   File "C:\Program Files\Python36\lib\site-packages\sqf\parser.py", line 572, in parse
>     tokens = [identify_token(x) for x in parse_strings_and_comments(tokenize(script))]
>   File "C:\Program Files\Python36\lib\site-packages\sqf\base_tokenizer.py", line 7, in tokenize
>     return list(filter(None, re.split(regex, statement)))
>   File "C:\Program Files\Python36\lib\re.py", line 212, in split
>     return _compile(pattern, flags).split(string, maxsplit)
> TypeError: expected string or bytes-like object

A minimal sqf example to trigger this error would be:
```sqf
isNil format []
```

**Comment by OfficialNoms** [comment]
I have also got this issue, any code that checks against [] will trigger this error and prevent the rest of the currently open file from being checked.

**Comment by LordGolias** [comment]
Would it work with 
```
code = 'x = isNil format ["x"];\n'
errors = sqf.analyzer.analyze(sqf.parser.parse(code))
```

I do not have sqflint atm in my computer, but it could be that it expects at least a full line (including EOL).
