### ISSUE TITLE
Private variable warning in lazy evaluation

### ISSUE THREAD

**Issue by WillWaywell** [LordGolias/sqf#5]
The following statement will produce a warning "Local variable ;_view' is not from this scope.":

```
private _view = cameraView;

if (!isNull objectParent player && {_view == "GUNNER"}) then {
};
```

What's strange however is that a warning is not produced in the following statement:
```
private _view = cameraView;

if (true && {_view == "GUNNER"}) then {
};
```

**Comment by jonpas** [comment]
Did you verify on latest commit? Should have been fixed with #3.

**Comment by WillWaywell** [comment]
Yes I've pulled and installed the latest commit (0b952c1b08514ed3ca5086e0c2aa9dc78a44ba08) using
`pip install -e .`

**Comment by WillWaywell** [comment]
Yes, pulled the latest commit (0b952c1b08514ed3ca5086e0c2aa9dc78a44ba08) and install using `pip install -e .`.
