### ISSUE TITLE
Select statement: false positive

### ISSUE THREAD

**Issue by WillWaywell** [LordGolias/sqf#6]
The following statement will produce an error of "Binary operator 'select' arguments must be [(Array,Number),(Array,Boolean),(String,Array),(Array,Code),(Config,Number),(Array,Array)] (lhs is String, rhs is Boolean)":
```
animationState player select [9, 3] in ["eva", "spr"]
```

Removing the 'in' check from the statement will no longer produce the error however:
```
animationState player select [9, 3]
```

Both statements work without error in-game.

**Comment by jonpas** [comment]
Are you sure this hasn't been fixed with commit 0b952c1b08514ed3ca5086e0c2aa9dc78a44ba08?

I am not sure if that's published on pip yet.

**Comment by WillWaywell** [comment]
Yes, pulled the latest commit (0b952c1) and install using `pip install -e .`.

**Comment by LordGolias** [comment]
This is a particular example of issue #7. I will close this one so we can focus on the broader problem there.
